import { platformBrowserDynamic } from '@angular/platform-browser-dynamic';

import { AppModule } from './app/app.module';
import { registerLicense } from '@syncfusion/ej2-base';


registerLicense('Mgo+DSMBaFt+QHJqVk1nQ1RbdF9AXnNLdFFxT2Jdby8Nf1dGYl9RQnZaQl9hTn9Wc0ZkUA==;Mgo+DSMBPh8sVXJ1S0R+X1pDaVpdX2NLfUN0T2FedV90ZCQ7a15RRnVfRF1mSXxRcURmXHpceQ==;ORg4AjUWIQA/Gnt2VFhiQlJPcUBHQmFJfFBmR2lbeFRxcEU3HVdTRHRcQltjTH5RdEJiXHpYdn0=;MjMwNzkxMUAzMjMxMmUzMDJlMzBsaGZXdUp0UWxoOHUzckxrVE1XYU1FN3lTbk9KemxWejdmakUwTzdud2xjPQ==;MjMwNzkxMkAzMjMxMmUzMDJlMzBnNk1sSGxtK3Fha1FNRnoxUkU4ZXJGWXZZSERJVzc2MlNycEo2VTBSWCs4PQ==;NRAiBiAaIQQuGjN/V0d+Xk9HfVhdWHxLflF1VWFTfVl6dVFWESFaRnZdQV1lSXtTdEdkWHpYcn1c;MjMwNzkxNEAzMjMxMmUzMDJlMzBaQURSSHBJeDdacUxGNTFtQUVGTVZ0ZytsTFozWkJ2MlRMS0Y1ZFVjRXY4PQ==;MjMwNzkxNUAzMjMxMmUzMDJlMzBjb0Rwb3Y3SU56WlliSHVzTXJpYUJLSGpDcVRRNlpnN2FsdDlnQ3REYnJFPQ==;Mgo+DSMBMAY9C3t2VFhiQlJPcUBHQmFJfFBmR2lbeFRxcEU3HVdTRHRcQltjTH5RdEJiXHlXcn0=;MjMwNzkxN0AzMjMxMmUzMDJlMzBWV2RZa00vazN5RzRCd1lUWDhkSzBZd2NVZ2tKdEV4T0JNOVdObDUzWkZvPQ==;MjMwNzkxOEAzMjMxMmUzMDJlMzBlVnFVK0hhbFdMeU9QalM3SndTQlRoYU4wNWJZTDZTa1lKTEc2RXpQall3PQ==;MjMwNzkxOUAzMjMxMmUzMDJlMzBaQURSSHBJeDdacUxGNTFtQUVGTVZ0ZytsTFozWkJ2MlRMS0Y1ZFVjRXY4PQ==');


platformBrowserDynamic().bootstrapModule(AppModule)
  .catch(err => console.error(err));
